/* Native XLSX dashboard and action table; no network or third-party dependencies. */
window.PlanExports=(()=>{
  'use strict';
  const names={pending:'Pendente',doing:'Em andamento',done:'Concluída',blocked:'Bloqueada'};
  const xml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
  const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';
  const serial=value=>value?(Date.parse(value+'T00:00:00Z')-Date.UTC(1899,11,30))/86400000:null;
  function today(){const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
  const deadline=a=>a.status==='done'?'Concluída':!a.end?'Sem prazo':a.end<today()?'Atrasada':a.end===today()?'Vence hoje':'No prazo';
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function build(p,task){
    const end=Math.max(7,p.actions.length+6),range=col=>`'Ações'!${col}7:${col}${end}`;
    let styles=[],fonts=[],fills=['FFFFFF','12263A','2075B8','EAF2F8','E2F4EA','FBE7E9','FFF2D9'],fontMap=new Map();
    function style(fill=0,color='26384B',bold=false,size=11,numFmt=0,align='left',border=0){const key=[color,bold,size].join('|');if(!fontMap.has(key)){fontMap.set(key,fonts.length);fonts.push({color,bold,size})}styles.push({fill:fill+2,font:fontMap.get(key),numFmt,align,border});return styles.length-1}
    const plain=style(),title=style(1,'FFFFFF',true,22),subtitle=style(3,'425B72',false,11),head=style(1,'FFFFFF',true,11,0,'left',1),body=style(0,'26384B',false,11,0,'left',1),center=style(0,'26384B',false,11,0,'center',1),date=style(0,'26384B',false,11,164,'center',1),done=style(4,'227447',true,11,0,'center',1),doing=style(3,'1D639C',true,11,0,'center',1),blocked=style(5,'A82436',true,11,0,'center',1),pending=style(6,'855D10',true,11,0,'center',1),metricLabel=style(3,'425B72',true,11,0,'center'),metric=style(3,'2075B8',true,26,0,'center'),percent=style(4,'227447',true,26,9,'center'),section=style(2,'FFFFFF',true,12),note=style(0,'60748A',false,11),percentSmall=style(0,'26384B',false,11,9,'center',1);
    function cell(ref,value,s=plain,formula){let content='';if(formula)content='<f>'+xml(formula)+'</f>';if(value==null||value==='')return `<c r="${ref}" s="${s}"${formula?' t="str"':''}>${content}${formula?'<v></v>':''}</c>`;if(typeof value==='number')return `<c r="${ref}" s="${s}">${content}<v>${value}</v></c>`;return formula?`<c r="${ref}" s="${s}" t="str">${content}<v>${xml(value)}</v></c>`:`<c r="${ref}" s="${s}" t="inlineStr"><is><t xml:space="preserve">${xml(value)}</t></is></c>`}
    const row=(n,cells,height=26)=>`<row r="${n}" ht="${height}" customHeight="1">${cells.join('')}</row>`;
    const origin=p.source?task(p.source):null,originText=origin?origin.projectTitle+' · '+origin.taskName:p.source?'Vínculo de origem indisponível':'Plano independente';
    const count=status=>p.actions.filter(a=>a.status===status).length,late=p.actions.filter(a=>deadline(a)==='Atrasada').length;
    const summaryRows=[row(1,[cell('A1',p.title,title)],35),row(2,[],18),row(3,[cell('A3','PLANO DE AÇÃO  |  '+new Date().toLocaleString('pt-BR'),subtitle)]),row(4,[],10)];
    const merges=['A1:J2','A3:J3'];const metrics=[['A','B','Total de ações',p.actions.length,`COUNT(${range('A')})`],['C','D','Concluídas',count('done'),`COUNTIF(${range('G')},"Concluída")`],['E','F','Em andamento',count('doing'),`COUNTIF(${range('G')},"Em andamento")`],['G','H','Pendentes',count('pending'),`COUNTIF(${range('G')},"Pendente")`],['I','J','Atrasadas',late,`COUNTIF(${range('H')},"Atrasada")`]];
    summaryRows.push(row(5,metrics.map(([a,b,label])=>{merges.push(`${a}5:${b}5`,`${a}6:${b}7`);return cell(a+'5',label,metricLabel)})),row(6,metrics.map(([a,b,label,value,f])=>cell(a+'6',value,metric,f)),34),row(7,[],18),row(8,[],12),row(9,[cell('A9','DISTRIBUIÇÃO POR STATUS',section),cell('F9','PROGRESSO DO PLANO',section)]));merges.push('A9:D9','F9:J9');
    summaryRows.push(row(10,[cell('A10','Status',head),cell('C10','Ações',head),cell('D10','Percentual',head)]));merges.push('A10:B10','F10:J12');
    const distribution=Object.entries(names).map(([k,v],i)=>{const r=i+11;merges.push(`A${r}:B${r}`);return row(r,[cell('A'+r,v,body),cell('C'+r,count(k),center,`COUNTIF(${range('G')},"${v}")`),cell('D'+r,p.actions.length?count(k)/p.actions.length:0,percentSmall,`IFERROR(C${r}/COUNT(${range('A')}),0)`)] )});
    // Keep every cell in its declared row; the progress card occupies F10:J12.
    summaryRows[summaryRows.length-1]=row(10,[cell('A10','Status',head),cell('C10','Ações',head),cell('D10','Percentual',head),cell('F10',p.actions.length?count('done')/p.actions.length:0,percent,`IFERROR(COUNTIF(${range('G')},"Concluída")/COUNT(${range('A')}),0)`)]);
    summaryRows.push(...distribution,row(16,[cell('A16','Origem: '+originText,subtitle)]),row(18,[cell('A18','SOBRE O PLANO',section)]),row(19,[cell('A19',p.description||'Sem descrição.',note)],48),row(21,[cell('A21','COMO USAR ESTE ARQUIVO',section)]),row(22,[cell('A22','Use a guia Ações para filtrar responsáveis, datas e status. Cabeçalho congelado e filtros estão disponíveis.',note)],32),row(23,[cell('A23','As datas são datas reais do Excel. Duração, prazo e indicadores são recalculados ao abrir o arquivo.',note)],32),row(24,[cell('A24','Este Excel é um relatório editável. Alterações nele não são sincronizadas com o app; para reimportar, use JSON.',note)],32));merges.push('A16:J16','A18:J18','A19:J20','A21:J21','A22:J22','A23:J23','A24:J24');
    const common='<sheetFormatPr defaultRowHeight="26"/>';
    const mergeXML=values=>`<mergeCells count="${values.length}">${values.map(ref=>`<mergeCell ref="${ref}"/>`).join('')}</mergeCells>`;
    const margins='<pageMargins left="0.3" right="0.3" top="0.4" bottom="0.4" header="0.2" footer="0.2"/><pageSetup paperSize="9" orientation="landscape" fitToWidth="1" fitToHeight="0"/>';
    const sheet1=`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="${ns}"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><dimension ref="A1:J24"/><sheetViews><sheetView workbookViewId="0" showGridLines="0"/></sheetViews>${common}<cols><col min="1" max="10" width="15" customWidth="1"/></cols><sheetData>${summaryRows.join('')}</sheetData>${mergeXML(merges)}${margins}</worksheet>`;
    const headers=['Nº','Ação','Responsável','Início','Término','Duração (dias)','Status','Prazo','Cronograma','Tarefa vinculada','Observações'];
    const actionRows=[row(1,[cell('A1',p.title,title)],35),row(2,[],18),row(3,[cell('A3',p.description||'Plano de ação — acompanhamento de responsáveis e prazos',subtitle)],32),row(4,[cell('A4','Exportado em '+new Date().toLocaleString('pt-BR')+' · '+originText,note)]),row(5,[],10),row(6,headers.map((h,i)=>cell(xlCol(i+1)+'6',h,head)),30)];
    for(let i=0;i<Math.max(1,p.actions.length);i++){
      const a=p.actions[i],r=i+7,t=a&&a.link?task(a.link):null,s=a?({done,doing,blocked,pending}[a.status]):body;
      actionRows.push(row(r,[cell('A'+r,a?i+1:null,center),cell('B'+r,a?.title,body),cell('C'+r,a?.owner,body),cell('D'+r,serial(a?.start),date),cell('E'+r,serial(a?.end),date),cell('F'+r,a?.start&&a.end?serial(a.end)-serial(a.start)+1:'',center,`IF(AND(ISNUMBER(D${r}),ISNUMBER(E${r})),E${r}-D${r}+1,"")`),cell('G'+r,a?names[a.status]:'',s),cell('H'+r,a?deadline(a):'',center,`IF(A${r}="","",IF(G${r}="Concluída","Concluída",IF(E${r}="","Sem prazo",IF(E${r}<TODAY(),"Atrasada",IF(E${r}=TODAY(),"Vence hoje","No prazo")))))`),cell('I'+r,t?.projectTitle||(a?.link?'Vínculo indisponível':'Independente'),body),cell('J'+r,t?.taskName,body),cell('K'+r,a?.notes,body)],48));
    }
    const cols=[7,48,24,14,14,15,21,18,30,34,58].map((width,i)=>`<col min="${i+1}" max="${i+1}" width="${width}" customWidth="1"/>`).join('');
    const sheet2=`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><dimension ref="A1:K${end}"/><sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane xSplit="2" ySplit="6" topLeftCell="C7" activePane="bottomRight" state="frozen"/><selection pane="bottomRight" activeCell="C7" sqref="C7"/></sheetView></sheetViews>${common}<cols>${cols}</cols><sheetData>${actionRows.join('')}</sheetData>${mergeXML(['A1:K2','A3:K3','A4:K4'])}<conditionalFormatting sqref="H7:H${end}"><cfRule type="cellIs" dxfId="0" priority="1" operator="equal"><formula>"Atrasada"</formula></cfRule><cfRule type="cellIs" dxfId="1" priority="2" operator="equal"><formula>"Concluída"</formula></cfRule></conditionalFormatting><dataValidations count="1"><dataValidation type="list" allowBlank="1" sqref="G7:G${end}"><formula1>"Pendente,Em andamento,Concluída,Bloqueada"</formula1></dataValidation></dataValidations>${margins}<tableParts count="1"><tablePart r:id="rId1"/></tableParts></worksheet>`;
    const styleXML=`<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="${ns}"><numFmts count="1"><numFmt numFmtId="164" formatCode="dd/mm/yyyy"/></numFmts><fonts count="${fonts.length}">${fonts.map(f=>`<font>${f.bold?'<b/>':''}<sz val="${f.size}"/><color rgb="FF${f.color}"/><name val="Segoe UI"/></font>`).join('')}</fonts><fills count="${fills.length+2}"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill>${fills.map(f=>`<fill><patternFill patternType="solid"><fgColor rgb="FF${f}"/></patternFill></fill>`).join('')}</fills><borders count="2"><border/><border><left/><right/><top/><bottom style="thin"><color rgb="FFDDE6EF"/></bottom></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="${styles.length}">${styles.map(s=>`<xf numFmtId="${s.numFmt}" fontId="${s.font}" fillId="${s.fill}" borderId="${s.border}" xfId="0" applyNumberFormat="1" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="${s.align}" vertical="center" wrapText="1"/></xf>`).join('')}</cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles><dxfs count="2"><dxf><font><color rgb="FFA82436"/></font><fill><patternFill patternType="solid"><fgColor rgb="FFFBE7E9"/></patternFill></fill></dxf><dxf><font><color rgb="FF227447"/></font><fill><patternFill patternType="solid"><fgColor rgb="FFE2F4EA"/></patternFill></fill></dxf></dxfs></styleSheet>`;
    const relationships=items=>`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${items.map(([id,type,target])=>`<Relationship Id="${id}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/${type}" Target="${target}"/>`).join('')}</Relationships>`;
    const table=`<?xml version="1.0" encoding="UTF-8"?><table xmlns="${ns}" id="1" name="PlanoDeAcao" displayName="PlanoDeAcao" ref="A6:K${end}" totalsRowShown="0"><autoFilter ref="A6:K${end}"/><tableColumns count="11">${headers.map((h,i)=>`<tableColumn id="${i+1}" name="${xml(h)}"/>`).join('')}</tableColumns><tableStyleInfo name="TableStyleMedium2" showFirstColumn="0" showLastColumn="0" showRowStripes="1" showColumnStripes="0"/></table>`;
    const files={'[Content_Types].xml':`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/tables/table1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.table+xml"/></Types>`,
      '_rels/.rels':relationships([['rId1','officeDocument','xl/workbook.xml']]),
      'xl/workbook.xml':`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Resumo" sheetId="1" r:id="rId1"/><sheet name="Ações" sheetId="2" r:id="rId2"/></sheets><definedNames><definedName name="_xlnm.Print_Area" localSheetId="0">'Resumo'!$A$1:$J$24</definedName><definedName name="_xlnm.Print_Area" localSheetId="1">'Ações'!$A$1:$K$${end}</definedName><definedName name="_xlnm.Print_Titles" localSheetId="1">'Ações'!$6:$6</definedName></definedNames><calcPr calcId="191029" fullCalcOnLoad="1"/></workbook>`,
      'xl/_rels/workbook.xml.rels':relationships([['rId1','worksheet','worksheets/sheet1.xml'],['rId2','worksheet','worksheets/sheet2.xml'],['rId3','styles','styles.xml']]),'xl/worksheets/sheet1.xml':sheet1,'xl/worksheets/sheet2.xml':sheet2,'xl/worksheets/_rels/sheet2.xml.rels':relationships([['rId1','table','../tables/table1.xml']]),'xl/styles.xml':styleXML,'xl/tables/table1.xml':table};
    return zipBlob(files);
  }
  function excel(p,task){try{download(build(p,task),cleanFileName(p.title)+'.xlsx')}catch(e){alert('Erro ao exportar Excel: '+e.message)}}
  function pdfHTML(p,task){const fmt=d=>d?d.split('-').reverse().join('/'):'—';return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${xml(p.title)}</title><style>@page{size:A4 landscape;margin:12mm}body{font-family:Arial,sans-serif;color:#26384b;font-size:10px}h1{font-size:22px;color:#12263a}header{border-bottom:3px solid #2075b8;padding-bottom:12px;margin-bottom:18px}p{white-space:pre-wrap}table{border-collapse:collapse;width:100%;table-layout:fixed}thead{display:table-header-group}th{background:#12263a;color:white;text-align:left}td,th{padding:8px;border-bottom:1px solid #dde6ef;overflow-wrap:anywhere;vertical-align:top}tr{break-inside:avoid}tbody tr:nth-child(even){background:#eaf2f8}.done{color:#227447}.late{color:#a82436}.link{font-size:9px;color:#60748a}</style></head><body><header><h1>${xml(p.title)}</h1><p>${xml(p.description)}</p><div>${p.actions.length} ações · ${p.actions.filter(a=>a.status==='done').length} concluídas · ${p.actions.filter(a=>deadline(a)==='Atrasada').length} atrasadas · ${new Date().toLocaleDateString('pt-BR')}</div></header><table><thead><tr><th style="width:25%">Ação / vínculo</th><th>Responsável</th><th>Início</th><th>Término</th><th>Status / prazo</th><th style="width:22%">Observações</th></tr></thead><tbody>${p.actions.map(a=>{const t=a.link?task(a.link):null;return `<tr><td>${xml(a.title)}${t?`<p class="link">${xml(t.projectTitle)} · ${xml(t.taskName)}</p>`:''}</td><td>${xml(a.owner)||'—'}</td><td>${fmt(a.start)}</td><td>${fmt(a.end)}</td><td class="${deadline(a)==='Atrasada'?'late':a.status==='done'?'done':''}">${names[a.status]}<br>${deadline(a)}</td><td>${xml(a.notes)}</td></tr>`}).join('')}</tbody></table></body></html>`}
  function pdf(p,task){const frame=document.createElement('iframe');frame.style.cssText='position:fixed;width:0;height:0;border:0';document.body.append(frame);frame.contentDocument.open();frame.contentDocument.write(pdfHTML(p,task));frame.contentDocument.close();setTimeout(()=>{frame.contentWindow.focus();frame.contentWindow.print();setTimeout(()=>frame.remove(),2000)},300)}
  return {excel,pdf,build,pdfHTML};
})();
