const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage(),report=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://script.google.com/**',r=>r.abort());await page.goto(process.env.GANTT_TEST_URL||'http://127.0.0.1:8765');
  const plan={id:'plan',title:'Plano PDF completo',description:'Descrição preservada',document:{participants:['Maria Silva','João Pereira'],agenda:'AGENDA ONE\nAGENDA TWO',notes:'DOCUMENT START '+Array(35).fill('Texto da reunião para preservar todas as informações.').join(' ')+' DOCUMENT END'},actions:Array.from({length:36},(_,i)=>({id:'a'+i,title:'ACTION '+String(i+1).padStart(3,'0'),owner:i%2?'João Pereira':'Maria Silva',start:'2026-10-05',end:'2026-10-16',status:['pending','doing','done','blocked'][i%4],notes:'NOTES '+String(i+1).padStart(3,'0')+' Observação detalhada, com duas linhas.\nSegunda linha.',...(i===0?{link:{projectId:'source',taskId:'t'}}:{})}))};
  await page.evaluate(p=>{
   window.testPlan=p;window.taskLookup=link=>link?{projectTitle:'Cronograma original',taskName:'Tarefa vinculada'}:null;
   ActionPlans.load([p,{id:'child',parentId:'plan',title:'Subplano filho',actions:[{id:'child-action',title:'SUBPLAN ACTION',owner:'Maria Silva',status:'pending',notes:'SUBPLAN NOTES',start:'2026-10-05',end:'2026-10-09'}]}]);ActionPlans.refresh();
  },plan);await page.click('#tabActions');const before=await page.evaluate(()=>JSON.stringify(ActionPlans.exportData()));
  // The real toolbar opens configuration, retaining scope and all document sections.
  await page.evaluate(()=>{GanttPrint.print=html=>window.printCapture=html});await page.click('#apPDF');assert(await page.locator('#planPdfPages').isVisible());await page.fill('#planPdfPages','3');await page.selectOption('#planPdfOrientation','portrait');await page.locator('.ap-modal button[type=submit]').click();await page.waitForFunction(()=>window.printCapture);
  let html=await page.evaluate(()=>printCapture);assert(html.includes('SUBPLAN ACTION')&&html.includes('DOCUMENT END')&&html.includes('Maria Silva'));assert(html.includes('data-plan-print-pages="3"'));assert(!html.includes('@page{size:A4 landscape'));assert.equal(await page.evaluate(()=>JSON.stringify(ActionPlans.exportData())),before);
  for(const orientation of ['landscape','portrait'])for(const pages of [1,2,3])for(const nativeLandscape of [true,false]){
   html=await page.evaluate(async options=>PlanPrint.prepare(PlanExports.pdfHTML(testPlan,taskLookup),options),{orientation,pages});await report.setContent(html);await report.emulateMedia({media:'print'});
   assert.equal(await report.locator('.plan-sheet').count(),pages);assert.equal(await report.locator('.action-title').filter({hasText:/^ACTION \d{3}$/}).count(),36);assert(html.includes('DOCUMENT START')&&html.includes('DOCUMENT END'));assert.equal(await report.locator('.status').count(),36);
   const pdf=await report.pdf({format:'A4',landscape:nativeLandscape,printBackground:true,preferCSSPageSize:false});assert.equal((pdf.toString('latin1').match(/\/Type\s*\/Page\b/g)||[]).length,pages,`${orientation} report, ${nativeLandscape?'landscape':'portrait'} paper, ${pages} pages`);fs.writeFileSync(`/tmp/plan-pdf-${orientation}-${nativeLandscape?'landscape':'portrait'}-${pages}.pdf`,pdf);
  }
  html=await page.evaluate(async()=>PlanPrint.prepare(PlanExports.pdfHTML(testPlan,taskLookup),{orientation:'landscape',pages:'auto'}));await report.setContent(html);assert(Number(await report.locator('body').getAttribute('data-plan-print-pages'))>1);const readableScale=Number(await report.locator('body').getAttribute('data-plan-print-scale'));assert(readableScale>.8,'Suggested pagination keeps readable font sizes');fs.writeFileSync('/tmp/plan-pdf-suggested.pdf',await report.pdf({format:'A4',landscape:true,printBackground:true}));await report.emulateMedia({media:'screen'});await report.screenshot({path:'/tmp/plan-pdf-suggested.png',fullPage:true});await report.emulateMedia({media:'print'});
  // Long observations continue across logical rows; text is preserved instead of truncated.
  html=await page.evaluate(async()=>{const p={...testPlan,actions:[{...testPlan.actions[0],notes:'LONG START '+Array(200).fill('Todas as observações devem continuar visíveis.').join(' ')+' LONG END'}]};return PlanPrint.prepare(PlanExports.pdfHTML(p,taskLookup),{pages:3,orientation:'landscape'})});await report.setContent(html);assert((await report.locator('.action-notes').count())>1);assert(html.includes('LONG START')&&html.includes('LONG END'));fs.writeFileSync('/tmp/plan-pdf-long.pdf',await report.pdf({format:'A4',landscape:true,printBackground:true}));
  // Empty plans, safe literal text, and requested orientation cancellation.
  html=await page.evaluate(async()=>PlanPrint.prepare(PlanExports.pdfHTML({title:'Plano vazio',actions:[]},()=>null),{pages:1,orientation:'portrait'}));await report.setContent(html);assert.equal(await report.locator('.plan-sheet').count(),1);assert(html.includes('No actions added'));const empty=await report.pdf({format:'A4',landscape:false});assert.equal((empty.toString('latin1').match(/\/Type\s*\/Page\b/g)||[]).length,1);
  html=await page.evaluate(async()=>PlanPrint.prepare(PlanExports.pdfHTML({title:'<script>alert(1)</script>',document:{notes:'<img src=x onerror=alert(1)>'},actions:[]},()=>null),{pages:1}));await report.setContent(html);assert.equal(await report.locator('script,img').count(),0);assert((await report.locator('.section-content').textContent()).includes('<img'));
  await page.uncheck('#apIncludeChildren');await page.evaluate(()=>{window.printCapture=null});await page.click('#apPDF');await page.fill('#planPdfPages','2');await page.locator('.ap-modal button[type=submit]').click();await page.waitForFunction(()=>printCapture);assert(!(await page.evaluate(()=>printCapture)).includes('SUBPLAN ACTION'));assert.equal(await page.evaluate(()=>JSON.stringify(ActionPlans.exportData())),before);
  await page.click('#apPDF');await page.click('#planPdfCancel');assert.equal(await page.locator('#planPdfPages').count(),0);assert.equal(await page.locator('[data-plan-measure]').count(),0);
  await page.setViewportSize({width:390,height:844});await page.click('#apPDF');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);assert(await page.locator('#planPdfPages').isVisible());await page.screenshot({path:'/tmp/plan-pdf-modal-mobile.png',fullPage:true});await page.click('#planPdfCancel');
  assert.deepEqual(errors,[]);console.log('PASS: plan PDF modal, exact 1/2/3 pages in native/report orientations, full actions/context/links/statuses, long-note continuation, subtree scope, safe text, source isolation, empty plans and mobile layout');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
