const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const today=new Date().toISOString().slice(0,10);
const day=n=>new Date(Date.parse(today+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
const task=(id,title,status='Em Andamento',extra={})=>({id,title,status,date:today,deadline:day(14),project:'R&D',priority:3,difficulty:2,notes:'Notas originais',tags:['tag'],subtasks:[{text:'Item original',completed:false}],recurrence:{frequency:'Nenhuma',daysOfWeek:[],daysOfMonth:[]},metadata:{preserved:'value'},...extra});
const fixture={tasks:[task('a','TAREFA ATIVA'),task('late','TAREFA ATRASADA','Em Andamento',{date:day(-5),deadline:day(-1)}),task('repeat','TAREFA RECORRENTE','Recorrente',{recurrence:{frequency:'Diária',daysOfWeek:[],daysOfMonth:[]}}),task('reserve','TAREFA RESERVA','Reserva'),task('done','TAREFA CONCLUÍDA','Concluída'),task('cancel','TAREFA CANCELADA','Cancelada')],settings:{projects:['R&D','Projeto B'],config:{alertYellow:7,alertOrange:3,alertRed:1,projectPriorities:{'R&D':4}}}};
const url=process.env.GANTT_TEST_URL||'http://127.0.0.1:8765';

(async()=>{
  const browser=await chromium.launch({headless:true});
  try{
    const page=await browser.newPage({viewport:{width:1320,height:900}}),errors=[],external=[];
    page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
    await page.route('https://script.google.com/**',r=>r.abort());
    await page.addInitScript(data=>{if(window===window.top && !localStorage.getItem('pf_todo_v1'))localStorage.setItem('pf_todo_v1',JSON.stringify(data))},fixture);
    page.on('request',r=>{if(!r.url().startsWith(new URL(url).origin)&&!r.url().includes('script.google.com'))external.push(r.url())});
    await page.goto(url);assert.equal(await page.locator('#appTabs button').allTextContents().then(a=>a.join('|')),'✅ Todo|✅ Todo novo|☀ Meu dia|Planos de ação|Cronogramas');
    assert.equal(await page.locator('#tabTodo').getAttribute('aria-selected'),'true');
    const originalUrl=await page.locator('#todoFrame').getAttribute('src');assert(originalUrl.includes('script.google.com'));
    await page.click('#tabTodoNative');const frame=page.frameLocator('#todoNativeFrame');
    await frame.getByRole('button',{name:'Nova Tarefa',exact:true}).waitFor();
    await page.waitForFunction(()=>document.getElementById('todoNativeFrame').contentWindow.TaskMaster);
    assert.equal(await page.locator('#todoNativeFrame').getAttribute('src'),'todo-native/index.html?v=20261008-my-day');
    assert(await page.locator('#toolbar').isHidden());assert(await page.locator('#scheduleHierarchyBar').isHidden());
    for(const label of ['Dashboard','Conflitos','Planejamento','Configurações'])assert(await frame.getByRole('button',{name:label,exact:true}).isVisible() || label==='Conflitos');
    const before=await page.evaluate(()=>JSON.stringify({projects,plans:ActionPlans.exportData()}));
    const card=title=>frame.locator('main .grid > div').filter({has:frame.getByRole('heading',{name:title,exact:true})}).first();
    assert.equal(await frame.getByRole('heading',{name:'TAREFA ATIVA',exact:true}).count(),1);
    assert.equal(await frame.getByRole('heading',{name:'TAREFA CONCLUÍDA',exact:true}).count(),0);
    await card('TAREFA ATIVA').getByRole('button',{name:/Subtarefas/}).click();
    await card('TAREFA ATIVA').locator('input[type=checkbox]').check();
    await page.waitForFunction(()=>NativeTodo.snapshot().tasks.find(t=>t.id==='a').subtasks[0].completed);
    await card('TAREFA ATIVA').getByPlaceholder('Adicionar subtarefa').fill('Novo item');
    await card('TAREFA ATIVA').getByRole('button',{name:'Incluir',exact:true}).click();
    await card('TAREFA ATIVA').getByTitle('Ver notas',{exact:true}).click();
    await card('TAREFA ATIVA').getByPlaceholder('Digite observações da tarefa').fill('Notas editadas');
    await card('TAREFA ATIVA').getByRole('heading',{name:'TAREFA ATIVA',exact:true}).click();
    await frame.locator('[data-task-id="a"] input[type=text]').first().fill('TAREFA RENOMEADA');
    await frame.locator('[data-task-id="a"] input[type=text]').first().press('Enter');
    await page.waitForFunction(()=>NativeTodo.snapshot().tasks.find(t=>t.id==='a').title==='TAREFA RENOMEADA');
    await card('TAREFA RENOMEADA').getByRole('button',{name:'Em Andamento',exact:true}).click();
    await card('TAREFA RENOMEADA').getByRole('button',{name:'Concluída',exact:true}).click();
    await page.waitForFunction(()=>NativeTodo.snapshot().tasks.find(t=>t.id==='a').status==='Concluída');
    assert.equal(await frame.getByRole('heading',{name:'TAREFA RENOMEADA',exact:true}).count(),0);
    await frame.locator('main select').nth(1).selectOption('Todos');
    assert.equal(await frame.getByRole('heading',{name:'TAREFA RENOMEADA',exact:true}).count(),1);
    assert.equal(await frame.getByRole('heading',{name:'TAREFA RESERVA',exact:true}).count(),1);
    await card('TAREFA RECORRENTE').getByRole('button',{name:'Avançar',exact:true}).click();
    await page.waitForFunction(date=>NativeTodo.snapshot().tasks.find(t=>t.id==='repeat').date===date,day(1));

    await frame.getByRole('button',{name:'Nova Tarefa',exact:true}).click();
    const form=frame.locator('form');
    await form.locator('input[type=text]').first().fill('NOVA TAREFA FIEL');
    await form.locator('select').first().selectOption('Projeto B');
    await form.getByPlaceholder('Adicionar item...').fill('Subtarefa do formulário');
    await form.getByPlaceholder('Adicionar item...').press('Enter');
    await form.locator('textarea').fill('Texto do formulário');
    await form.getByRole('button',{name:'Salvar Tarefa',exact:true}).click();
    await page.waitForFunction(()=>NativeTodo.snapshot().tasks.some(t=>t.title==='NOVA TAREFA FIEL'));
    await frame.getByRole('button',{name:'Editar tarefa NOVA TAREFA FIEL',exact:true}).click();
    await form.locator('input[type=text]').first().fill('TAREFA EDITADA');
    await form.getByRole('button',{name:'Salvar Tarefa',exact:true}).click();
    await frame.getByRole('button',{name:'Planejamento',exact:true}).click();
    assert(await frame.getByRole('heading',{name:'Planejar por Semana'}).isVisible());
    const plannerRow=frame.locator('tbody tr').filter({hasText:'TAREFA EDITADA'});
    await plannerRow.locator('td').nth(2).locator('button').first().click();
    await plannerRow.locator('td').nth(2).locator('button').nth(2).click();
    await frame.getByRole('button',{name:'Programar',exact:true}).click();
    await page.waitForFunction(()=>NativeTodo.snapshot().tasks.find(t=>t.title==='TAREFA EDITADA').date!==undefined);
    await frame.getByRole('checkbox',{name:'Agrupar por projeto'}).check();
    assert((await frame.locator('tbody').innerText()).includes('Projeto B'));
    await frame.getByRole('button',{name:/^Conflitos/}).click();assert(await frame.getByRole('heading',{name:'Tarefas com Conflitos'}).isVisible());
    assert.equal(await frame.getByRole('heading',{name:'TAREFA ATRASADA',exact:true}).count(),1);
    await frame.getByRole('button',{name:'Configurações',exact:true}).click();
    await frame.locator('input[type=number]').first().fill('9');
    await page.waitForFunction(()=>NativeTodo.snapshot().settings.config.alertYellow===9);
    const dates=await page.evaluate(()=>Object.fromEntries(NativeTodo.snapshot().tasks.map(t=>[t.id,t.date])));
    await frame.getByRole('button',{name:'+1 Dia',exact:true}).click();
    await page.waitForFunction(original=>NativeTodo.snapshot().tasks.find(t=>t.id==='late').date!==original,dates.late);
    const afterShift=await page.evaluate(()=>NativeTodo.snapshot());
    for(const id of ['a','reserve','done','cancel'])assert.equal(afterShift.tasks.find(t=>t.id===id).date,dates[id]);
    assert.equal(afterShift.tasks.find(t=>t.id==='a').notes,'Notas editadas');assert.equal(afterShift.tasks.find(t=>t.id==='a').metadata.preserved,'value');
    let download=page.waitForEvent('download');await frame.getByRole('button',{name:'Exportar Backup',exact:true}).click();
    await (await download).saveAs('/tmp/todo-native-original-format.json');
    const exported=JSON.parse(fs.readFileSync('/tmp/todo-native-original-format.json','utf8'));
    assert.equal(exported.tasks.length,7);assert.equal(exported.config.alertYellow,9);
    assert(exported.tasks.some(t=>t.status==='Reserva'));assert(exported.tasks.some(t=>t.status==='Cancelada'));
    assert.equal(await page.evaluate(()=>JSON.stringify({projects,plans:ActionPlans.exportData()})),before);
    await page.reload();await page.click('#tabTodoNative');
    await page.waitForFunction(()=>document.getElementById('todoNativeFrame').contentWindow.TaskMaster);
    assert.equal(await page.evaluate(()=>NativeTodo.snapshot().tasks.length),7);
    await frame.getByRole('button',{name:'Dashboard',exact:true}).click();
    await frame.getByRole('button',{name:'Excluir tarefa TAREFA EDITADA',exact:true}).click();
    await page.waitForFunction(()=>NativeTodo.snapshot().tasks.length===6);
    await frame.getByRole('button',{name:'Configurações',exact:true}).click();
    await frame.locator('input[type=file]').setInputFiles('/tmp/todo-native-original-format.json');
    await page.waitForFunction(()=>NativeTodo.snapshot().tasks.length===7);

    await page.evaluate(()=>{ActionPlans.load([{id:'all-plan',title:'Plano geral',actions:[{id:'action',title:'AÇÃO GERAL',status:'done',start:'',end:'',owner:'',notes:''}]}]);saveStore()});
    download=page.waitForEvent('download');await page.click('#ntBackupAll');await (await download).saveAs('/tmp/projectflow-backup-geral.json');
    const full=JSON.parse(fs.readFileSync('/tmp/projectflow-backup-geral.json','utf8'));
    assert.equal(full.type,'projectflow-backup');assert(full.projects.length>0);assert.equal(full.actionPlans[0].actions[0].status,'done');assert.equal(full.todo.tasks.length,7);
    assert(!JSON.stringify(full).includes('pf_github'));assert(!Object.hasOwn(full,'token'));
    const count=full.projects.length;
    await page.evaluate(()=>{ActionPlans.load([]);NativeTodo.restoreData({tasks:[],settings:{projects:['R&D'],config:{}}})});
    const backupBeforeRestore=page.waitForEvent('download');
    assert.equal(await page.evaluate(data=>WorkspaceBackup.restore(data),full),true);await backupBeforeRestore;
    assert.equal(await page.evaluate(()=>NativeTodo.snapshot().tasks.length),7);assert.equal(await page.evaluate(()=>ActionPlans.exportData().length),1);assert.equal(await page.evaluate(()=>projects.length),count);
    const preserved=await page.evaluate(()=>JSON.stringify(WorkspaceBackup.snapshot(),(k,v)=>['exportedAt','updatedAt'].includes(k)?undefined:v));
    const malformed=JSON.parse(JSON.stringify(full));malformed.todo.tasks.push({...malformed.todo.tasks[0]});
    assert(await page.evaluate(data=>{try{WorkspaceBackup.restore(data);return false}catch{return true}},malformed));
    assert.equal(await page.evaluate(()=>JSON.stringify(WorkspaceBackup.snapshot(),(k,v)=>['exportedAt','updatedAt'].includes(k)?undefined:v)),preserved);
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
    await frame.getByRole('button',{name:'Nova Tarefa',exact:true}).click();assert(await frame.getByRole('button',{name:'Salvar Tarefa',exact:true}).isVisible());
    await page.screenshot({path:'/tmp/todo-native-mobile.png'});await frame.getByRole('button',{name:'Cancelar',exact:true}).click();
    await page.click('#tabTodo');assert.equal(await page.locator('#todoFrame').getAttribute('src'),originalUrl);assert(await page.locator('#todoNativePanel').isHidden());
    await page.click('#tabActions');assert(await page.locator('#todoNativeToolbar').isHidden());
    await page.click('#tabGantt');assert(await page.locator('#main').isVisible());
    assert.deepEqual(external,[]);assert.deepEqual(errors,[]);
    console.log('PASS: five tabs/default original, locally hosted faithful Todo, CRUD, inline titles/notes/subtasks/status, recurrence, filters, weekly planner, conflicts, settings/mass shifts, JSON compatibility/persistence, unified backup/restore/validation, metadata/source isolation and mobile');
  }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
